### ISSUE TITLE
设置下的切换.env问题

### ISSUE THREAD

**Issue by pomelo-ink** [nonebot/cli-plugin-webui#12]
在设置下只能切换两个分别为[".env", ".env.prod"],但实际有三个[".env", ".env.prod", ".env.dev"]
![image](https://github.com/nonebot/cli-plugin-webui/assets/99504275/6be5fb0c-7748-4492-b4a8-6c2fbec27da4)
![image](https://github.com/nonebot/cli-plugin-webui/assets/99504275/93718535-73a8-4708-a9ea-0eece67279ef)

**Comment by Kyomotoi** [comment]
这里刚重新看了下，切换不止在侧边栏处，图2中的“播放” btn 作用效果也是切换
