### ISSUE TITLE
删除实例，screen被干掉

### ISSUE THREAD

**Issue by MRDHR** [nonebot/cli-plugin-webui#4]
删除nonebot2实例，后台screen被干掉

**Comment by Kyomotoi** [comment]
请提供更完整的报告，例如：
- 系统信息
- bug发生后程序主体是否还在运行

还是如所说的，在 screen 内运行 cli webui，然后在 webui 上删除实例后连带跑着 cli webui 的 screen 一起被干了

**Comment by MRDHR** [comment]
系统信息： ubuntu 22.04 lts, e3-1240v3, 32G, 6T

在screen里运行cli webui，在webui上删除实例后，screen被干掉了。

**Comment by MRDHR** [comment]
不对，当时的实例没能删除。是提示删除失败了。然后去查screen 发现screen被杀了

**Comment by Kyomotoi** [comment]
...有点摸不着头脑，请等下一个版本更新后再尝试看看 bug 是否依存

**Comment by MRDHR** [comment]
好的，下次更新后 我在screen运行的时候 获取一下日志

**Comment by Kyomotoi** [comment]
已发布新版本，请更新后再次尝试

**Comment by MRDHR** [comment]
大佬，我想问一下。现在新版本的nonebot2 qsign方案快失效了。有啥新方案来做qq机器人么？

**Comment by MRDHR** [comment]
这次我没有用screen启动，直接nb ui的

**Comment by MRDHR** [comment]
完整的日志如下
` [?] What do you want to do? Run NB CLI UI.
INFO     23-11-21 08:47:42 runners:asyncio:44 | Started server process [516094]
INFO     23-11-21 08:47:42 base_events:asyncio:603 | Waiting for application startup.
INFO     23-11-21 08:47:42 application:nb_cli_plugin_webui:68 | Starting NoneBot CLI WebUI.
INFO     23-11-21 08:47:42 application:nb_cli_plugin_webui:69 | NoneBot CLI WebUI version: 0.3.0
INFO     23-11-21 08:47:45 base_events:asyncio:603 | Application startup complete.
INFO     23-11-21 08:47:45 base_events:asyncio:603 | Uvicorn running on http://0.0.0.0:12345 (Press CTRL+C to quit)
INFO     23-11-21 08:48:25 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:54804 - "/ HTTP/1.1" 
INFO     23-11-21 08:48:25 base_events:asyncio:1909 | GET     | 200 | 154.40.40.220:54812 - "/assets/index-e3b5f700.js HTTP/1.1" 
INFO     23-11-21 08:48:25 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:54818 - "/assets/index-d58ec682.css HTTP/1.1" 
INFO     23-11-21 08:48:26 applications:fastapi:276 | GET     | 403 | 154.40.40.220:54828 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:48:26 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:54822 - "/api/status/platform/ws WebSocket"
INFO     23-11-21 08:48:26 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:48:26 applications:fastapi:276 | GET     | 403 | 154.40.40.220:54840 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:48:26 applications:fastapi:276 | GET     | 403 | 154.40.40.220:54854 - "/api/file/list?path= HTTP/1.1" 
INFO     23-11-21 08:48:26 base_events:asyncio:1909 | GET     | 200 | 154.40.40.220:54870 - "/assets/material-symbols-outlined-c57680c1.woff2 HTTP/1.1" 
INFO     23-11-21 08:48:26 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:48:26 applications:fastapi:276 | GET     | 403 | 154.40.40.220:54874 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:48:27 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:54888 - "/favicon.ico HTTP/1.1" 
INFO     23-11-21 08:48:32 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:34694 - "/api/auth/login HTTP/1.1" 
INFO     23-11-21 08:48:32 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:34710 - "/api/status/platform/ws WebSocket"
INFO     23-11-21 08:48:32 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:48:32 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34720 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:48:32 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34730 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:48:32 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34738 - "/api/file/list?path= HTTP/1.1" 
INFO     23-11-21 08:48:33 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34748 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:48:53 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:57804 - "/api/project/check_toml?project_dir=%2Froot%2FMrdBot2%2F HTTP/1.1" 
INFO     23-11-21 08:49:06 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:50556 - "/api/project/add HTTP/1.1" 
INFO     23-11-21 08:49:06 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:50572 - "/api/process/log/KsfdDAvcmz/ws WebSocket"
INFO     23-11-21 08:49:06 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:49:12 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:49:25 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:37798 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:49:27 base_events:asyncio:603 | GET     | 404 | 154.40.40.220:37810 - "/api/process/log/history?log_id=KcVMqd&log_count=50 HTTP/1.1" 
INFO     23-11-21 08:49:27 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:37818 - "/api/process/log/KcVMqd/ws WebSocket"
INFO     23-11-21 08:49:27 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:49:28 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:49:37 base_events:asyncio:1909 | POST    | 404 | 154.40.40.220:43954 - "/api/process/run?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:49:50 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:46622 - "/api/store/nonebot/list?module_type=plugin&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:49:50 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:49:53 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:34712 - "/api/status/platform/ws WebSocket"
INFO     23-11-21 08:49:53 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:49:53 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34728 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:49:53 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34740 - "/api/file/list?path= HTTP/1.1" 
INFO     23-11-21 08:49:53 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34742 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:49:53 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34758 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:49:54 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34770 - "/api/project/config/meta/detail?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:49:55 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34784 - "/api/project/config/nonebot/detail?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:49:55 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:49:55 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34806 - "/api/project/config/env/list?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:49:55 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:34798 - "/api/project/config/nonebot/plugins/detail?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:50:18 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:38890 - "/api/status/platform/ws WebSocket"
INFO     23-11-21 08:50:18 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:50:18 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:38904 - "/api/file/list?path= HTTP/1.1" 
INFO     23-11-21 08:50:18 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:38894 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:50:18 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:38918 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:50:18 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:38926 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:50:27 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:35670 - "/api/store/nonebot/list?module_type=plugin&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:50:28 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:50:28 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:35682 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:50:29 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:35696 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:50:31 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:37776 - "/api/store/nonebot/install?env=.env&project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:50:31 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:37788 - "/api/process/log/iMDSSPJs/ws WebSocket"
INFO     23-11-21 08:50:31 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:50:35 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:50:36 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:37790 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:50:39 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:37800 - "/api/store/nonebot/install?env=.env&project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:50:39 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:37814 - "/api/process/log/ANSGmNZM/ws WebSocket"
INFO     23-11-21 08:50:39 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:50:43 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:50:44 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:48324 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=KcVMqd&is_search=false HTTP/1.1" 
INFO     23-11-21 08:50:47 routing:starlette:341 | CLIENT  | [accepted] | 154.40.40.220:48338 - "/api/status/platform/ws WebSocket"
INFO     23-11-21 08:50:47 _asyncio:anyio:204 | connection open
INFO     23-11-21 08:50:47 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:48352 - "/api/project/list HTTP/1.1" 
INFO     23-11-21 08:50:47 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:48354 - "/api/file/list?path= HTTP/1.1" 
INFO     23-11-21 08:50:47 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:48370 - "/api/store/nonebot/list?module_type=driver&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
INFO     23-11-21 08:50:47 base_events:asyncio:603 | GET     | 200 | 154.40.40.220:48382 - "/api/store/nonebot/list?module_type=adapter&page=0&project_id=&is_search=false&show_all=true HTTP/1.1" 
WARNING  23-11-21 08:50:48 process:nb_cli_plugin_webui:119 | Possible process pid=515883 found, terminated.
WARNING  23-11-21 08:50:48 process:nb_cli_plugin_webui:119 | Possible process pid=516094 found, terminated.
INFO     23-11-21 08:50:48 base_events:asyncio:1909 | POST    | 200 | 154.40.40.220:48388 - "/api/process/run?project_id=KcVMqd HTTP/1.1" 
INFO     23-11-21 08:50:48 base_events:asyncio:636 | Shutting down
INFO     23-11-21 08:50:49 base_events:asyncio:1909 | Waiting for background tasks to complete. (CTRL+C to force quit)
INFO     23-11-21 08:50:49 _eventloop:anyio:68 | connection closed
INFO     23-11-21 08:50:49 base_events:asyncio:603 | Waiting for application shutdown.
INFO     23-11-21 08:50:49 application:nb_cli_plugin_webui:84 | Check and stop all running processes.
INFO     23-11-21 08:50:49 process:nb_cli_plugin_webui:129 | Process pid=516922 terminated.
INFO     23-11-21 08:50:49 base_events:asyncio:603 | Application shutdown complete.
INFO     23-11-21 08:50:49 runners:asyncio:44 | Finished server process [516094] `

**Comment by MRDHR** [comment]
这个是第二次webui后，我启动实例立马程序立马退出了
[log1.txt](https://github.com/nonebot/cli-plugin-webui/files/13420615/log1.txt)

**Comment by Kyomotoi** [comment]
这可能是 uvicorn 那边的问题

**Comment by Kyomotoi** [comment]
> 大佬，我想问一下。现在新版本的nonebot2 qsign方案快失效了。有啥新方案来做qq机器人么？

目前没啥稳定的方案，且用且珍惜吧，或者考虑即将到来的官方 bot

**Comment by MRDHR** [comment]
官方bot的方案我试过好几个框架，没成功过

**Comment by Kyomotoi** [comment]
> 官方bot的方案我试过好几个框架，没成功过

目前处于内测状态，估计得等上几个月

**Comment by MRDHR** [comment]
难受，账号被风控了。要想想怎么搞

**Comment by MRDHR** [comment]
风控问题解决了，发布的信息格式被腾讯定向屏蔽了
