### ISSUE TITLE
扫描完能否跳过安装依赖

### ISSUE THREAD

**Issue by ABKQPO** [nonebot/cli-plugin-webui#5]
进入安装依赖后控制他弹出以下内容
Python-dotenv could not parse statement starting at line 42
D:\NoneBot\ABK\.venv\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Python-dotenv could not parse statement starting at line 42
Python-dotenv could not parse statement starting at line 42
Python-dotenv could not parse statement starting at line 42
Python-dotenv could not parse statement starting at line 42
Python-dotenv could not parse statement starting at line 42
Python-dotenv could not parse statement starting at line 42
D:\NoneBot\ABK\.venv\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Python-dotenv could not parse statement starting at line 42
D:\NoneBot\ABK\.venv\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Python-dotenv could not parse statement starting at line 42
D:\NoneBot\ABK\.venv\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Python-dotenv could not parse statement starting at line 42
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Config
NICKNAME
  field required (type=value_error.missing)
RECV_GROUP_ID
  field required (type=value_error.missing)
D:\NoneBot\ABK\.venv\lib\site-packages\trio\_core\_multierror.py:511: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(

**Comment by Kyomotoi** [comment]
安装依赖是必要的，除非你已使用 venv 为项目创建虚拟环境。nb webui 强制每一个 NoneBot 实例启用 venv 虚拟环境
出现这个大概率是实例在读取 .env 数据时，其数据类型对不上
同时你的项目还出现了包冲突
