### ISSUE TITLE
获取 NoneBot 插件设置失败：undefined

### ISSUE THREAD

**Issue by huangzhitian** [nonebot/cli-plugin-webui#7]
![image](https://github.com/nonebot/nb-cli/assets/129321746/b79b6dcf-db8f-4f22-add8-78fbcccb7960)

**Comment by Kyomotoi** [comment]
请打开 webui 后按下 F12 启动 `devtools`，切到 network

然后打开 webui 设置页，看看 network 中的内容**有无标红**，如有，请截图

**Comment by huangzhitian** [comment]
> 请打开 webui 后按下 F12 启动 `devtools`，切到 network
> 
> 然后打开 webui 设置页，看看 network 中的内容**有无标红**，如有，请截图
我不懂干嘛了，又自己好了，谢谢了

**Comment by Tamamoimoto** [comment]
![Image](https://github.com/user-attachments/assets/d0c8044a-e770-42c3-b327-cd7059a61406)
